<?php
use FAQ\FAQCommon\Util;
use Doctrine\ODM\MongoDB\DocumentNotFoundException;
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/message/more.css' );
$currentUser = Util::getCurrentUser ();
$currentUserName = Util::getUserName ( $currentUser );
// add titile
$this->headtitle ( "Thông báo của " . $currentUserName . " | " . $currentUser->getDateCreated ()->getTimestamp () );
// setting meta description
$this->placeholder ( 'description' )->append ( "Các thống từ 123hoidap.vn tới " . $currentUserName );
?>
<div class="faq_content">
	<div id="faq_message_detail_header">
		<ul class="nav nav-tabs" id="faq_message_index_nav">
			<li class="active"><a
				href="<?php echo $this->basepath("/message");?>">Thông báo</a></li>
			<li class=""><a
				href="<?php echo $this->basepath("/message/chat-box");?>">Tin nhắn</a></li>
		</ul>
	</div>
	<div id="faq_content_notify">
		<ul class="list-notify">
<?php


$groupNotifies = array ();
if (count ( $data ['notifies'] ) > 0) {
	$offset = $data ['offset'];
	$length = $data ['length'];
	$notifies = $data ['notifies'];
	// var_dump($data);
	for($j = $length + $offset - 1; $j >= $offset; $j --) {
// 	    Util::writeLog($j);
	    try {
	    if ($j < 0) {
			break;
		}
		
		$notify = $notifies [$j];
		if(!empty($notify)){
		$document = $notify->getQuestion ();
		if(!empty($document)){
		
		
		$notifyContent = $notify->getContent ();
		/* @var $notify \FAQ\FAQEntity\Notify */
		
		$userCreateNotify = $notify->getUserCreateNotify ();
		$timeUpdateNotify = $notify->getDateUpdated ()->getTimestamp () * 1000;
		// var_dump($userCreateNotify->getId());
		$avatar = $userCreateNotify->getAvatar ();
		
		$imageID = $avatar->getId ();
		$userName = $userCreateNotify->getFirstName () . " " . $userCreateNotify->getLastName ();

		$contentType = $avatar->getContentType ();

		$extentionFile = Util::getTypeFile ( $contentType );
		$titleFileSeo = Util::convertUrlFileName ( $userName, $extentionFile );

		$titleSeo = "";
		$typeCode = $notify->getType ();

			$type = "question";
			$documentID = $document->getId ();
			$titleSeo = Util::convertUrlSeo ( $document->getTitle () );

		$documentID_typeCode = $documentID . "_" . $typeCode;
		$isContain = isset ( $this->_elements [$documentID_typeCode] ) || array_key_exists ( $documentID_typeCode, $groupNotifies );
		// group
		if ($isContain == FALSE) {
			$groupNotifies [$documentID_typeCode] = array (
					"type" => $type,
					"documentID" => $documentID,
					"titleSeo" => $titleSeo,
					"imageID" => $imageID,
					"titleFileSeo" => $titleFileSeo,
					"userName" => $userName,
					"timeUpdateNotify" => $timeUpdateNotify,
					"shortNotifyContent" => $notifyContent,
					"notifyContent" => $userName . "> " . $notifyContent,
					"total_user" => 1
			);
		} elseif ($isContain == TRUE) {
			$newNotify = array ();
			$oldNotify = $groupNotifies [$documentID_typeCode];
			$newNotifyTotalUser = $oldNotify ['total_user'] + 1;
			if ($newNotifyTotalUser < 4) {
				$oldNotifyUserName = $oldNotify ["userName"];
				$isContaintName = strpos ( $oldNotifyUserName, $userName ) > - 1;
				if ($isContaintName == false) {
					$newNotifyUserName = $userName . ", " . $oldNotifyUserName;
				}
			}
			$newNotify = array (
					"type" => $type,
					"documentID" => $documentID,
					"titleSeo" => $titleSeo,
					"imageID" => $imageID,
					"titleFileSeo" => $titleFileSeo,
					"userName" => $newNotifyUserName,
					"timeUpdateNotify" => $timeUpdateNotify,
					"shortNotifyContent" => $notifyContent,
					"notifyContent" => $userName . "> " . $notifyContent . ", " . $oldNotify ["notifyContent"],
					"total_user" => $newNotifyTotalUser
			);

			$groupNotifies [$documentID_typeCode] = $newNotify;
		}
		
		}
		}
	    } catch (\Exception $e) {
			Util::writeLog($e->getMessage());
			break;
		}
	}
	
	
}
// var_dump($groupNotifies);
foreach ( $groupNotifies as $key => $groupNotify ) :
	$groupNotifyType = $groupNotify ['type'];
	$groupNotifyDocumentID = $groupNotify ['documentID'];
	$groupNotifyTitleSeo = $groupNotify ['titleSeo'];
	$groupNotifyImageID = $groupNotify ['imageID'];
	$groupNotifyTitleFileSeo = $groupNotify ['titleFileSeo'];
	$groupNotifyUserName = $groupNotify ['userName'];
	$groupNotifyTtotalUser = $groupNotify ['total_user'];
	if ($groupNotifyTtotalUser > 3) {
		$groupNotifyTtotalUserOther = $groupNotifyTtotalUser - 3;
		$groupNotifyUserName = $groupNotifyUserName . " và " . $groupNotifyTtotalUserOther . " người khác";
	}
	$groupNotifyShortContent = mb_substr ( $groupNotify ['shortNotifyContent'], 0, 70, 'UTF-8' ) . "...";
	$groupNotifyContent = $groupNotify ['notifyContent'];
	$groupNotifyTimeUpdateNotify = $groupNotify ['timeUpdateNotify'];
	?>
	<li><a
				href="<?php echo $this->basepath("/$groupNotifyType/detail/$groupNotifyDocumentID/$groupNotifyTitleSeo");?>"
				target="_blank">

					<div class="pull-left">
						<img class="img-rounded" id="faq_img_user_profile"
							style="-webkit-user-select: none"
							src="<?php echo $this->basepath("/media/get-image/images/$groupNotifyImageID/$groupNotifyTitleFileSeo")?>">
					</div>
					<div class="pull-right faq_wrap_content_more_notify"
						title="<?php echo $groupNotifyContent;?>">
						<span><b><?php echo  $groupNotifyUserName;?></b></span> <span><?php echo $groupNotifyShortContent;?></span>
						<br> <span class="text-muted  faq_post_time faq_time_notify"
							post-time=<?php echo $groupNotifyTimeUpdateNotify; ?>></span>
					</div>
			</a></li>


<?php

endforeach
;


?>



		</ul>
	</div>
	<script type="text/javascript">
settimeUpdate();
</script>
	<style>
.faq_wrap_content_more_notify {
	width: 92%;
}
</style>
</div>