<?php
use FAQ\FAQCommon\Util;
if(isset($error)){
    echo $error;
}else{
$context=$this;

/* @var $reply \FAQ\FAQEntity\Reply */
$replyn_id= $reply->getId();
$replyn_content = $reply->getContent();
$replyn_user=$reply->getCreateBy();
$replyn_user_name = $replyn_user->getFirstName() . ' ' . $replyn_user->getLastName();
$replyn_userId = $replyn_user->getId();
$replyn_date = $reply->getDateUpdated();
$avatar=$replyn_user
->getAvatar();
$reply_user_avatarId =$avatar
->getId();

$contentType = $avatar->getContentType();

$extentionFile = Util::getTypeFile($contentType);
$titleFileSeo = Util::convertUrlFileName($replyn_user_name,$extentionFile);

?>

<a href="/member/profile/<?php echo $replyn_userId; ?>/<?php echo Util::getUserNameSeo($replyn_user);?>" class="postActor"> <img
	class=" avatar img-circle faq_img_top_member"
	user="<?php echo $replyn_userId; ?>" style="-webkit-user-select: none"
	src="/media/get-image/images/<?php echo $reply_user_avatarId."/".$titleFileSeo; ?>" />

</a>
<div class="faq_sub_reply media">
	<div>
		<a class="profileName   media-heading" target="_blank">
			<?php echo $replyn_user_name; ?>
		</a>
		<span class="text-muted  faq_post_time pull-right" post-time="<?php echo
						$replyn_date->sec*1000; ?>"></span>
		<div class=" fsm">
			<div class="postText  media-body">
				<?php echo $context->escapehtml($replyn_content); ?>
			</div>
			<div class="stat_elem">
				<div class="action_links fsm">
					<a role="button" class="faq_btn_reply_comment"
						faq-data-comment="<?php echo "REPLY1+,".$replyn_id?>">Phản hồi</a>
				</div>
			</div>
		</div>
	</div>
	<div class="postReplies"></div>
</div>
<?php }?>