<h1>Khởi dựng từ khóa</h1>
<div class="col-md-12">
<button id="faq_init_key_word" type="button"
	data-loading-text="Đang update..." class="btn btn-primary">Khởi tạo key
	word</button>
</div>
<br/>
<h1>Cập nhật từ khóa theo ngày</h1>
<div class="col-md-12" style="border: 1px solid;">
<div role="form" class="col-md-5">
			<div class="form-group">
				<label >Từ ngày</label>
				<input id="faq_imp_job_fromdate" type="date" class="form-control" placeholder="Từ ngày" autocomplete="off">

			</div>
			<div class="form-group">
				<label >Đến ngày</label>
				<input id="faq_imp_job_todate" type="date" class="form-control" placeholder="Đến ngày" autocomplete="off">
			</div>

			<div class="form-group">
                    <label>Tên collection</label><br>
                    <select id="faq_imp_job_type"  name="type">
                          <option value="USER">USER</option>
                          <option value="QUESTION">QUESTION</option>
                          <option value="LOCATION">LOCATION</option>
                          <option value="SKILL">SKILL</option>
                    </select>
                    </div>
			<button id="faq_update_key_word" type="button"
	data-loading-text="Đang update..." class="btn btn-primary">Cập nhật key
	word từ câu hỏi mới</button>
		</div>

</div>
<script type="text/javascript">
$("#faq_init_key_word").click(function(){
var btn = $('#faq_init_key_word');
btn.button('loading');
$.ajax({
//	async:false,
	url : basePath + "/admin/phpjob/init-keyword",
	type : "POST",
	dataType : "json",
	success : function(data) {
		if(data.status==1){
			console.log("reset");
			btn.button('reset');
		}
	},
	error : function() {
		bootbox.alert("cập nhật không thành công!");
		btn.button('reset');
		console.log("AJAX request was a failure");
	}
});

});

$("#faq_update_key_word").click(function(){
	var btn = $('#faq_update_key_word');
	btn.button('loading');
	var fromDate=$("#faq_imp_job_fromdate").val();
	var toDate=$("#faq_imp_job_todate").val();
	var type=$("#faq_imp_job_type").val();
// 	alert("fromDate:"+fromDate+"---toDate: "+toDate);
	$.ajax({
//		async:false,
		url : basePath + "/admin/phpjob/update-keyword",
		type : "POST",
		dataType : "json",
		data: {
			fromDate:fromDate,
			toDate:toDate,
			type:type
	     	   },
		success : function(data) {
			if(data.status==1){
				console.log("reset");
				btn.button('reset');
			}
		},
		error : function() {
			bootbox.alert("cập nhật không thành công!");
			btn.button('reset');
			console.log("AJAX request was a failure");
		}
	});

	});
</script>