<meta charset="utf-8">
<div style="width:50%;margin-left:25%;">
    <div style="margin-top:100px"></div>
    <img src="/images/notice-error.png" style="float:left;"  />
    <div style="float:left;font-size:20px;margin-top:64px;width:600px;font-style:italic;color:red;">
        Không tìm thấy service phục vụ cho request của bạn.
    </div>
    
</div>
<a style="display:none" id="url_back" href="/"></a>
<script>
         function redirect(){
             document.getElementById('url_back').click();
         }
         setTimeout('redirect()', 2000);
</script>