<form class="navbar-form navbar-left" role="search"
	action="/home/search" method="get" name="search-bar" id="search-bar"
	role="search">
	<div class="form-group">
		<input type="text" class="form-control" name="q"
			id="faq_txt_key_search"
			placeholder="Tìm kiếm tất cả mọi thứ...">

	</div>
	<button type="submit" class="btn btn-default" name="submit"
		id="faq_search" value="search">search</button>
</form>