<h4 class="faq_top">Sử dụng tag hiệu quả</h4>
<div style="padding-left: 10px;padding-right: 10px">
<p>
	Để b&agrave;i viết, c&acirc;u trả lời của bạn được li&ecirc;n kết đến
	những b&agrave;i viết kh&aacute;c một c&aacute;ch hiệu quả.<br />Bạn
	c&oacute; thể sử dụng Tag, <br />Tag thường l&agrave; c&aacute;c danh từ
	ri&ecirc;ng, danh từ chung, những từ, cụm từ c&oacute; &yacute; nghĩa
	nổi bật trong c&acirc;u.
</p>
<p>V&iacute; dụ: #H&agrave;-Nội, #Android, #Đ&agrave; Nẵng</p>
</div>
<center><a href="/tag/">Xem danh sách nổi bật>></a></center>
