<h4 class="faq_top">123hoidap.vn khuyến khích</h4>
<ul>
	<li>Chia sẻ những gì bạn có</li>
	<li>Luân lịch sự, tôn trọng mọi người</li>
	<li>Nội dung chia sẻ chất lượng</li>
	<li>Dẫn nguồn tham khảo</li>
	<li>Luân đặt câu hỏi trong đúng chủ đề</li>

</ul>

<h4 class="faq_top">123hoidap.vn không khuyến khích</h4>

<ul>
	<li>Lợi dụng hệ thống</li>
	<li>Vi phạm pháp luật</li>
	<li>Đăng câu hỏi trùng lặp</li>
	<li>Cư xử khiếm nhã</li>

</ul>
<center><a href="/support/term" style="text-align: center;">Xem nguyên tắc cộng đồng>></a></center>
