<div id="top-hashtag" class="panel panel-primary">
    <?php
        echo $this->partial('/web/home/top-hashtag.phtml');
    ?>
</div>
<div id="top-subject" class="panel panel-primary">
    <?php
        echo $this->partial('/web/home/top-subject.phtml');
    ?>
</div>

<div id="top-member" class="panel panel-primary">
    <?php
        echo $this->partial('/web/home/top-member.phtml');
    ?>
</div>
<div id="top-face-member-like" class="panel panel-primary">
    <div class="fb-like-box" data-href="https://www.facebook.com/123hoidapvn" data-width="300" data-height="600" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
</div>