<div id="top-answer-chart" class="panel panel-primary">
    <?php
    echo $this->partial('/web/home/chart-answer.phtml');
    ?>
</div>
<div class="faq_navbar_fixed">
<div id="faq-tearm" class="panel panel-primary">

  <?php
    echo $this->partial('/web/home/top-tearm.phtml');
    ?>
</div>

<div id="top-tag" class="panel panel-primary">
    <?php
    echo $this->partial('/web/home/top-tutorial-tag.phtml');
    ?>
</div>
</div>