<?php
use FAQ\FAQEntity\User;
use FAQ\FAQCommon\FAQParaConfig;
echo $this->doctype ();
?>
<html lang="vi_VN">
<head><meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php
echo $this->headMeta ( 'description', $this->placeholder ( 'description' ) . $this->headMetaDesc )->
// ->appendHttpEquiv('Content-Type',
// 'text/html; charset=UTF-8')
appendHttpEquiv ( 'Content-Language', 'vi-VN' );

        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/qapolo_logo_mini.ico'))
            ->prependStylesheet($this->basePath() . '/css/icons.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
            ->prependStylesheet($this->basePath() . '/css/footer.css')
            ->prependStylesheet($this->basePath() . '/css/layout.css')
            ->prependStylesheet($this->basePath() . '/css/common.css')
            ->prependStylesheet($this->basePath() . '/css/prettify.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-tagsinput.css')
            ->prependStylesheet($this->basePath() . '/css/docs.css')
            ->prependStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox.css')
//             ->prependStylesheet($this->basePath() . '/css/smoothness/jquery-ui-1.10.3.custom.css')


        ;?>

        <!-- Scripts -->
        <?php

        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/common.js')
            ->prependFile($this->basePath() . '/js/jquery.cookie.js')
//             ->prependFile($this->basePath() . '/js/mathjax/MathJax.js?config=TeX-MML-AM_HTMLorMML&locale=vi')

//             ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->appendFile($this->basePath() . '/js/prettify.js')
            ->appendFile($this->basePath() . '/js/jqBootstrapValidation.js')
//             ->appendFile($this->basePath() . '/js/bootstrap-tagsinput-angular.js')
//             ->appendFile($this->basePath() . '/js/typeahead.min.js')
//             ->appendFile($this->basePath() . '/js/bootstrap-tagsinput.js')
            ->prependFile($this->basePath() . '/js/bootbox.js')
            ->prependFile($this->basePath() . '/js/moment2.2.1.js')
            ->prependFile($this->basePath() . '/js/jquery-2.0.3.js')
            ->appendFile($this->basePath() . '/js/fixto.min.js')
            ->appendFile($this->basePath() . '/js/jquery.anchor.js')
        ->appendFile($this->basePath() . '/js/jquery.autocomplete.js')
        ->appendFile($this->basePath() . '/js/jquery.fancybox.js')
        ->appendFile($this->basePath() . '/js/faq_fancybox.js')
        ;
       echo $this->partial("/util/init-jsvariable.phtml");
        ?>




<style>
#faq_tour_nav {
	height: 60px;
/* 	margin-top: 5px; */
	color: black;
}
#faq_tour_about{
	margin-top: 5px;
}
</style>

<script type="text/javascript">
var isAllowed=true;
var basePath='<?php echo $this->basePath();?>';
var baseUrl='<?php echo $this->url();?>';
var domain= '123hoidap.vn';
var imgAjaxLoad="<div class='container'><center><img  src='<?php echo $this->basePath("/images/ajax-loader.gif")?>'> </center></div>";
var statusFollow="<?php echo FAQParaConfig::statusFollow?>";
var statusUnfollow="<?php echo FAQParaConfig::statusUnfollow?>";;
var actionFollow="<?php echo FAQParaConfig::actionFollow?>";
var actionUnfollow="<?php echo FAQParaConfig::actionUnfollow?>";
</script>
</head>


<body>


<!-- 	<div class="container panel panel-primary" > -->

		<?php echo $this->content; ?>
<!-- 	</div> -->




</body>
</html>