 <?php
use FAQ\FAQCommon\Util;
$this->headLink()
->prependStylesheet($this->basePath() . '/css/subject/index.css');

$this->headScript()
->appendFile($this->basePath() . '/js/bsa.js')
->appendFile($this->basePath() . '/js/subject/index.js')
;

//add titile
 $this->headtitle("Chủ đề của bài viết, đặt câu hỏi");
 // setting meta description
//push from controller to layout before
?>


<script type="text/javascript">
var faq_url_paging="<?php echo $this->basepath("/subject/list-subject")?>";
var totalLoad=1;
var step=48;
var faq_from_paging=totalLoad*step;
var faq_to_paging=(totalLoad+1)*step;
var faq_data_paging="keyword=&from="+faq_from_paging+"&to="+faq_to_paging;

var totalSubject=<?php echo $totalSubject?>;
var faq_action="<?php echo $actionName;?>";
</script>



<div class="faq_content">
	<div>
		<div class="form-inline pull-left faq_search_subject" role="form">
			<div class="form-group faq_imp_search_subject">
				<label class="sr-only" for="faq_lbl_search_subject">Tìm kiếm chủ đề</label>
				<input type="text" class="form-control" id="faq_txt_search_subject"
					placeholder="Tìm kiếm chủ đề" name="search_subject">
			</div>
			<button class="btn btn-default" id="faq_btn_search_subject">Tìm</button>
		</div>
	</div>
	<div class="faq_header_subject">
		<h4>Danh sách chủ đề</h4>
	</div>
    <div id="faq_postswrapper">
    <?php echo $this->partial('/web/subject/list-subject.phtml');?>
    </div>
</div>
<div id="faq_loadmoreajaxloader" style="display: none;">
	<div class='faq_container'>
		<center><img
			src='<?php echo $this->basePath("/images/ajax-loader.gif")?>'>

	</div>
</div>
