
<div id="faq_ask_now_create"
	class="col-lg-9 col-md-9 col-sm-9 col-xs-12 faq_padding_left_none faq_padding_right_none ">
    	<?php echo $this->partial("/web/question/ask-now.phtml");?>
</div>
<div
	class="col-lg-3 col-md-3 col-sm-3 col-xs-12 faq_padding_left_none faq_padding_right_none visible-md  visible-lg visible-sm">
	<div id="faq-tearm">

  <?php
		echo $this->partial ( '/web/home/top-tearm.phtml' );
		?>
</div>

	<div id="top-tag">
    <?php
				echo $this->partial ( '/web/home/top-tutorial-tag.phtml' );
				?>
</div>
</div>