<div class="faq_div_user_static">
<table>
<?php
use FAQ\FAQCommon\Util;
foreach ($users as $key => $user) :
    /* @var $user \FAQ\FAQEntity\User */
$userID=$user->getId();

$avatar=$user->getAvatar();
$avatarID= $avatar ->getId();

$contentType = $avatar->getContentType();

$extentionFile = Util::getTypeFile($contentType);
$titleFileSeo = Util::convertUrlFileName(Util::getUserName($user),$extentionFile);
    ?>
	<tr>
		<td>
			<a style="text-decoration: none" href="/member/profile/<?php echo $userID; ?>/<?php echo Util::getUserNameSeo($user);?>" >
			<img class="img-circle faq_img_user_static"
				user="<?php echo $userID; ?>" style="-webkit-user-select: none"
				src="/media/get-image/images/<?php echo $avatarID."/".$titleFileSeo; ?>" />
			&nbsp;&nbsp;<?php echo $user->getFirstName();?>
			&nbsp;&nbsp;/&nbsp;<?php echo Util::getUserRankText($user)?>&nbsp;(<span style="color:red;font-size:9px;font-style:italic;"><?php echo $user->getTotalRankPoint();?>đ</span>)
			</a>
		</td>
	</tr>
<?php endforeach;?>
</table>
</div>
