<?php
use Zend\Json\Json;

?>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script src="/js/amcharts/amcharts.js" type="text/javascript"></script>
        <script type="text/javascript">

            var chartQuestion;

            var chartDataQuestion = <?php echo Json::encode($chartAllQuestion);?>;

            AmCharts.ready(function () {
                // PIE CHART
                chartQuestion = new AmCharts.AmPieChart();
                chartQuestion.dataProvider = chartDataQuestion;
                chartQuestion.titleField = "status";
                chartQuestion.valueField = "total";
                chartQuestion.outlineColor = "#FFFFFF";
                chartQuestion.outlineAlpha = 0.8;
                chartQuestion.outlineThickness = 2;
                // this makes the chart 3D
                chartQuestion.depth3D = 15;
                chartQuestion.angle = 30;

                // WRITE
                chartQuestion.write("chartdiv_question");
            });

        </script>

<h1>Báo cáo tổng hợp câu hỏi</h1>
<h1><a href="http://123hoidap.vn/admin/question/index">Chi tiết câu hỏi</a></h1>
<div class="col-md-12">
<?php var_dump($chartAllQuestion);?>
</div>
<div class="col-md-12">
<div id="chartdiv_question" style="width: 100%; height: 400px;"></div>
<div id="chartPerDayQuestion" style="width: 100%; height: 400px;"></div>
</div>




<script>
var ChartPerDayQuestion;

var ChartPerDayQuestionData = [];
var totalQuestion=0;



AmCharts.ready(function () {
	$.each(<?php echo Json::encode($chartPerDayQuestion);?>, function(key,array) {
		var  dateUpdated=new Date(array.dateUpdated);
		totalQuestion=totalQuestion+Number(array.totalQuestion);
		ChartPerDayQuestionData.push({
	            date: dateUpdated,
	            totalQuestion: Number(array.totalQuestion)
	        });


	});

    // SERIAL CHART
    ChartPerDayQuestion = new AmCharts.AmSerialChart();
    ChartPerDayQuestion.pathToImages = "/js/amcharts/images/";
    ChartPerDayQuestion.dataProvider = ChartPerDayQuestionData.sortBy(function(o){ return o.date; });
    ChartPerDayQuestion.categoryField = "date";

    // data updated event will be fired when chart is first displayed,
    // also when data will be updated. We'll use it to set some
    // initial zoom
    ChartPerDayQuestion.addListener("dataUpdated", zoomChartPerDayQuestion);

    // AXES
    // Category
    var categoryAxis = ChartPerDayQuestion.categoryAxis;
    categoryAxis.parseDates = true; // in order char to understand dates, we should set parseDates to true
    categoryAxis.minPeriod = "DD"; // as we have data with minute interval, we have to set "mm" here.
    categoryAxis.gridAlpha = 0.07;
    categoryAxis.axisColor = "#DADADA";

    // Value
    var valueAxis = new AmCharts.ValueAxis();
    valueAxis.gridAlpha = 0.07;
    valueAxis.title = "Biểu đồ tăng trưởng câu hỏi theo ngày";
    ChartPerDayQuestion.addValueAxis(valueAxis);

    // GRAPH
    var graph = new AmCharts.AmGraph();
    graph.type = "line"; // try to change it to "column"
    graph.title = "red line";
    graph.valueField = "totalQuestion";
    graph.lineAlpha = 1;
    graph.lineColor = "#d1cf2a";
    graph.fillAlphas = 0.3; // setting fillAlphas to > 0 value makes it area graph
    ChartPerDayQuestion.addGraph(graph);

    // CURSOR
    var chartCursor = new AmCharts.ChartCursor();
    chartCursor.cursorPosition = "mouse";
    chartCursor.categoryBalloonDateFormat = "DD/MM/YYYY";
    ChartPerDayQuestion.addChartCursor(chartCursor);

    // SCROLLBAR
    var chartScrollbar = new AmCharts.ChartScrollbar();

    ChartPerDayQuestion.addChartScrollbar(chartScrollbar);

    // WRITE
    ChartPerDayQuestion.write("chartPerDayQuestion");
});





// this method is called when chart is first inited as we listen for "dataUpdated" event
function zoomChartPerDayQuestion() {
    // different zoom methods can be used - zoomToIndexes, zoomToDates, zoomToCategoryValues
    ChartPerDayQuestion.zoomToIndexes(ChartPerDayQuestionData.length - 40, ChartPerDayQuestionData.length - 1);
}
</script>
