<?php
//setting title for page
$this->headtitle("Liên hệ");
// setting meta description
$this->placeholder('description')
->append("Liên hệ với ban quản trị 123hoidap.vn để được trợ giúp");
?>
<div class="faq_content">
<h1 style="text-align: center;">Li&ecirc;n hệ với ban quản trị 123hoidap.vn</h1>
<p>&nbsp; &nbsp; Xin ch&acirc;n th&agrave;nh cảm ơn bạn đ&atilde; sử dụng dịch vụ của ch&uacute;ng t&ocirc;i!</p>
<p>&nbsp; &nbsp; Mọi &yacute; kiến đ&oacute;ng g&oacute;p của bạn xin vui l&ograve;ng gửi tới địa chỉ sau&nbsp;<a href="mailto:support@123hoidap.vn?subject=Thư%20g&oacute;p%20&yacute;" target="_top">support@123hoidap.vn</a>.</p>
<p>&nbsp; &nbsp; Ch&uacute;ng t&ocirc;i sẽ xem x&eacute;t v&agrave; phản hồi lại trong thời gian sớm nhất c&oacute; thể.</p>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Ban quản trị 123hoidap.vn</p>
<p>&nbsp;</p>
</div>