<?php
$this->headScript ()->appendFile ( $this->basePath () . '/js/typeahead.min.js' )->appendFile ( $this->basePath () . '/js/tag/index.js' )?>
<script type="text/javascript">

var tags="";
</script>
<?php echo $error;?>
<div class="faq_content col-lg-12 col-md-12 col-sm-12 col-xs-12">
	<form role="form" method="post" action="/tag/create"
		enctype="multipart/form-data">
		<div class="form-group">
			<label for="faq_InputEmail1">Tên Tags</label> <input name="tag_name"
				type="text" class="form-control" id="faq_tag_name"
				placeholder="Tên của tag nhỏ hơn 25 ký tự, nếu có 2 từ nên sử dụng dấu gạch ngang '-' nối lại. VD: may-tinh">
		</div>
		<div class="form-group">
			<label for="faq_tag_relationship">Tag liên quan</label> <input
				name="tag_relationship" type="text" class="form-control"
				id="faq_tag_relationship"
				placeholder="Những tag đồng nghĩa với tag trên">
			<div id="faq_data_tag"></div>
		</div>

		<div class="form-group">
			<label for="faq_desc">Mô tả chi tiết</label>
			<textarea id="faq_tag_desc" name="tag_desc" class="form-control"
				rows="3"></textarea>
			<p class="help-block">Mô tả chi tiết và tag trên giúp thành viên khác
				dễ dàng hiểu hơn.</p>
		</div>
		<div class="form-group">
			<label for="faq_avatar">Phân loại</label>
			 <select name="type"
				class="form-control" style="width: 300px">

				<option value="popular">Thông thường</option>
				<option value="location">Nơi công tác, học tập</option>
				<option value="member">Thành viên</option>
				<option value="kill">Kỹ năng cá nhân</option>
			</select>
		</div>
		<div class="form-group">
			<label for="faq_avatar">Ảnh đại diện</label> <input name="tag_avatar"
				type="file" id="tag_avatar">
			<p class="help-block">ví dụ: win8 sử dụng logo của win8 làm ảnh đại
				diện.</p>
		</div>
		<button id="faq_btn_submit_create_tag" type="submit"
			class="btn btn-primary">Tạo</button>
	</form>
</div>