<?php use FAQ\FAQCommon\Appcfg;
use FAQ\FAQCommon\FAQParaConfig;
echo $this->doctype(); ?>
<html lang="vi_VN">
<head><meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
        <?php  echo $this->headTitle($this->translate('Hỏi đáp | Hướng dẫn | QApolo'))->setSeparator(' | ')->setAutoEscape(false)?>

        <!-- Le styles -->
        <?php

        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/qapolo_logo_mini.ico'))
            ->prependStylesheet($this->basePath() . '/css/icons.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
            ->prependStylesheet($this->basePath() . '/css/footer.css')
            ->prependStylesheet($this->basePath() . '/css/layout.css')
            ->prependStylesheet($this->basePath() . '/css/common.css')
            ->prependStylesheet($this->basePath() . '/css/prettify.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-tagsinput.css')
            ->prependStylesheet($this->basePath() . '/css/docs.css')
//             ->prependStylesheet($this->basePath() . '/css/smoothness/jquery-ui-1.10.3.custom.css')
            ;?>

        <!-- Scripts -->
        <?php

        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/common.js')
//             ->prependFile($this->basePath() . '/js/mathjax/MathJax.js?config=TeX-MML-AM_HTMLorMML&locale=vi')

//             ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->appendFile($this->basePath() . '/js/prettify.js')
            ->appendFile($this->basePath() . '/js/jqBootstrapValidation.js')
//             ->appendFile($this->basePath() . '/js/bootstrap-tagsinput-angular.js')
//             ->appendFile($this->basePath() . '/js/typeahead.min.js')
//             ->appendFile($this->basePath() . '/js/bootstrap-tagsinput.js')
            ->prependFile($this->basePath() . '/js/bootbox.js')
            ->prependFile($this->basePath() . '/js/moment2.2.1.js')
            ->prependFile($this->basePath() . '/js/jquery-2.0.3.js')
        ->appendFile($this->basePath() . '/js/jquery.autocomplete.js');;
        ?>

<body>
                       <?php
					     echo $this->content;
					  ?>
</body>
<footer>
<?php echo $this->inlineScript() ?>
</footer>
</html>