<?php

// add titile
$this->headtitle ( "Giới thiệu về 123hoidap.vn" );
// setting meta description
$this->placeholder ( 'description' )->append ( "Giới thiệu về 123hoidap.vn là gì? Mục đích, ý nghĩa của hệ thống hỏi đáp, chia sẻ bài viết hướng dẫn chuyên sâu" );

?>
<div id="faq_tour_nav" class="col-md-12  pull-left navbar   navbar-fixed-top bs-docs-nav">
	<div class="col-md-2  pull-left">
		<a role="button" type="button" class="btn btn-info btn-lg  pull-right " href="/tour/follow-member">
			<span class="glyphicon glyphicon-arrow-left"></span>
		</a>
	</div>
	<div class="col-md-8  pull-left">
		<center>
			<h2>BƯỚC 4/5-THÍCH VÀ CHIA SẺ 123hoidap.vn</h2>
		</center>
	</div>
	<div class="col-md-2">
		<a role="button" class="btn btn-info btn-lg pull-left" href="/tour/community-guideline">
			<span class="glyphicon glyphicon-arrow-right"></span>
		</a>
	</div>

</div>
<div id="faq_tour_about" class="col-md-12  pull-left" style="margin-top: 56px;">
<div class="col-md-12  pull-left">
<h4>CLICK like 123hoidap.vn trên facebook để cập nhật tốt hơn</h4>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=207763216014035";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like-box" data-href="https://www.facebook.com/pages/K%E1%BA%BFt-n%E1%BB%91i-%C4%91am-m%C3%AA-Chia-s%E1%BA%BB-tri-th%E1%BB%A9c/389510794515662" data-width="1100" data-height="350" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
</div>
<div class="col-md-12 faq_wrap_content">
<h4>CLICK share để chia sẻ cùng bạn bè</h4>
<div class="fb-share-button" data-href="http://123hoidap.vn/" data-type="button_count"></div>
</div>
</div>

