<script type="text/javascript" src="/js/page.js"></script>
<script type="text/javascript" src="/js/login.js"></script>
<div id="login-contain-social" style="margin-top: 5px"></div>
	<form id="form-login" method="post" role="form">
		<div class="form-group">
			<div class="col-lg-12">
				<a href="<?php echo $this->facebook_login_url;?>"
					title="Đăng nhập bằng tài khoản Facebook"><img
					class="img-circle faq-img-openid"
					src="/images/logo/logo_facebook.jpg" /></a> <a
					href="<?php echo $this->twitter_login_url;?>"
					title="Đăng nhập bằng tài khoản Twitter"><img
					class="img-circle faq-img-openid"
					src="/images/logo/logo_tiwtter.jpg" /></a> <a href="#"
					title="Đăng nhập bằng tài khoản Google+"><img
					class="img-circle faq-img-openid"
					src="/images/logo/logo_googleplus.jpg" /></a>
<!-- 			   <a href="#" -->
<!-- 					title="Đăng nhập bằng tài khoản Yahoo"><img -->
<!-- 					class="img-circle faq-img-openid" src="/images/logo/logo_yahoo.jpg" /></a> -->
<!-- 				<a href="#" title="Đăng nhập bằng tài khoản ZingMe"><img -->
<!-- 					class="img-circle faq-img-openid" -->
<!-- 					src="/images/logo/logo_zingme.jpg" /></a> -->
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-12">
				<input name='email' type="text" class="form-control"
					valid_type="require email" valid_label="Địa chỉ Email"
					placeholder="Địa chỉ email">
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-12">
				<input name='password' type="password" valid_type="require"
					valid_label="Mật khẩu" class="form-control" placeholder="Mật khẩu">
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-3">
				<button id="login-submit" class="btn btn-default" >Đăng
					nhập</button>
			</div>
			<div class="col-lg-9">
				<div style="font-size: 9px; font-style: italic; text-align: center">
					<span>(*Chưa có tài khoản)</span><br /> <a href="/user/signup"
						style="font-size: 15px; font-style: italic">Đăng ký</a>
				</div>

			</div>
			<label class="col-lg-9 control-label">&nbsp;</label>
		</div>

		<div>
			<div class="col-lg-12">
				<div
					style="font-style: italic; border-bottom: 1px #CBDDDD solid; padding-bottom: 3px; margin-top: 80px;">
					<a href="#tro-giup">Trợ giúp</a>&nbsp;<span style="color: #CBDDDD">|</span>
					<a href="/user/forget-password">Quên mật khẩu</a>
				</div>

			</div>
		</div>
	</form>