<?php
use FAQ\FAQCommon\Util;

    $active = "change_password";
    $this->viewmodel()->active = $active;
    echo $this->partial("/web/user/setting-menu.phtml");
?>
<?php
    $member = $this->user;
    $name=Util::getUserName($member);

    $email = $member->getEmail();
     $this->headTitle($name.' | Thông tin tài khoản'." | ".$member->getDateCreated()->getTimestamp());
?>
<script type="text/javascript" src="/js/bootbox.js"></script>
<script type="text/javascript" src="/js/page.js"></script>
<form class="form-horizontal" id="change-password" role="form" style="margin-top:20px">
<!--     <div class="form-group"> -->
<!--          <label  class="col-lg-3 control-label">Mật khẩu cũ</label> -->
<!--          <div class="col-lg-5"> -->
<!--               <input name="old_password"  class="form-control"  placeholder="Mật khẩu cũ" valid_type="require" valid_label="Mật khẩu cũ" valid_label="Mật khẩu cũ"> -->
<!--          </div> -->
<!--     </div> -->
    <div class="form-group">
         <label  class="col-lg-3 control-label">Mật khẩu mới</label>
         <div class="col-lg-5">
              <input name="new_password" type="password"  class="form-control"  placeholder="Mật khẩu mới" valid_type="length" valid_label="Mật khẩu mới" valid_min=6 valid_max=25>
         </div>
    </div>
    <div class="form-group">
         <label  class="col-lg-3 control-label">Ghõ lại mật khẩu mới</label>
         <div class="col-lg-5">
              <input name="new_password_repeat" type="password" class="form-control"  placeholder="Mật khẩu mới nhập lại" valid_type="length" valid_label="Mật khẩu mới nhập lại" valid_min=6 valid_max=25>
        </div>
    </div>
    <div class="form-group">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
       		  <label  class="col-lg-3 control-label">Thay đổi email</label>
         </div>
          <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
              <input value="<?php echo $email; ?>" name="email" disabled  class="form-control"  placeholder="Email của bạn" valid_type="require email" valid_label="Địa chỉ email">
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
              <input type="checkbox" name="change_email" class="form-control"  />
          </div>
    </div>
    <div class="form-group">
         <label  class="col-lg-3 col-md-3 control-label"></label>
         <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
              <button name="save"  class="form-control btn btn-warning" >Cập nhật</button>
         </div>
    </div>
 </form>
 <style>
 .header_title{
    	font-size:25px;
    	font-style: italic;
    	color:#327518;
    	border-bottom:1px gray solid;
    	margin-bottom:10px;
    	width:100%;
    }
 </style>
 <script>
      // on submit
      $('#change-password').submit(function(evt){
    	  evt.preventDefault();
    	  var isValid = validateit('change-password','beside',false,false);
    	  if(!isValid) return;
//     	  var old_password = $('#change-password [name="old_password"]')[0].value;
    	  var new_password = $('#change-password [name="new_password"]')[0].value;
    	  var new_password_repeat = $('#change-password [name="new_password_repeat"]')[0].value;
    	  if(new_password!=new_password_repeat){
    		  $('#change-password .notice_text').remove();
      		   $('#change-password').prepend("<li style='list-style:none' class='notice_error_text notice_text'>* " + 'Mật khẩu bạn cung cấp không khớp' + '</li>');
      		   $('#change-password [name="new_password"]').addClass('ui-state-error');
      		   $('#change-password [name="new_password_repeat"]').addClass('ui-state-error');
      		   isValid = false;
      		   return;
    	  }
    	  // change password - commit

    	  $.ajax({
        	   url: '/user/change-password',
        	   type: 'post',
        	   data: {email: $('#change-password [name="email"]')[0].value,  new_password: new_password}
    	  }).done(function(data){
        	  if(data.toString().trim()=='saved'){
        		  bootbox.alert("Thông tin tài khoản được cập nhật thành công!", function() {
    				  document.location.href = "/user/change-password";
    			  });
    			  return;
        	  }
        	  if(data.toString().trim()=='email_used'){
        		  bootbox.alert("<li style='list-style:none' class='notice_error_text notice_text'>* " + 'Email này đã được dùng. Thông tin không được cập nhật' + '</li>');
    			  return;
        	  }
        	  if(data.toString().trim()=='password_not_match'){
        		   $('#change-password .notice_text').remove();
        		   $('#change-password').prepend("<li style='list-style:none' class='notice_error_text notice_text'>* " + 'Mật khẩu bạn cung cấp không đúng' + '</li>');
//         		   $('#change-password [name="old_password"]').addClass('ui-state-error');
        	  }
    	  });
      });

      // check change email
      $('#change-password [name="change_email"]').change(function(evt){
          var checked = $(this).prop('checked');
          console.log(checked);
          if(checked){
        	  $('#change-password [name="email"]').attr('disabled',false);
          }else{
        	  $('#change-password [name="email"]').attr('disabled',true);
          }
      });
 </script>