<?php  use Zend\Form\Element\Captcha;
echo $this->headTitle('Quên mật khẩu - 123hoidap.vn'); ?>
	  <a href="/">
<div id="login-contain-left-head">
	  <a href="/">
			<img class="faq_logo" src="/images/logo/logo_qapolo.png" width="95px">
	</a>
	  <div style="float:left;text-align:center;width:50%;margin-left:25%">
	   <span style="font-size: 50px;color: #3AAD48;font-weight: bold;font-style: italic;">Q</span><span style="font-size: 30px;font-weight: bold;">APOLO.COM</span><br/>
	   <span style="font-size: 25px;font-style: italic">Mọi câu hỏi đều có câu trả lời.</span>
	  </div>
</div>
	  </a>
<br/>
<?php if($this->status=='new' || $this->status=='not_valid' || $this->status=='email_not_exist'){?>
<form id="forget-password-form"  method="post" role="form" ">
        <div id="forget-password-form-title" style="border-bottom: 1px rgba(132, 167, 148, 0.06) solid;text-align: center;font-weight:bold" >Khôi phục mật khẩu đăng nhập - 123hoidap.vn</div>

       <div class="col-lg-5" >
             <?php echo $this->recap->getHTML(); ?>
       </div>
       <?php if($this->message){?><span style="font-size: 13px;font-style: italic;color: red;float:right">(*<?php echo $this->message;?>)</span><?php } ?>
        <div class="col-lg-6" >
            <div class="form-group">
                <div class="col-lg-10">
                    <input name='email' type="text" class="form-control" valid_type="require email" valid_label="Địa chỉ Email"
        			placeholder="Địa chỉ email của bạn">
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-5">
                     <button name="submit"  class="form-control"  class="btn btn-default" >Khôi phục</button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-6">
                     <a style="font-size:11px" href="/user/login">Quay lại đăng nhập</a>
                </div>
            </div>
       </div>

</form>
<?php }else{?>
<h1 style="font-size:30px;text-align:center;color:green"><?php echo $this->message;?></h1>
<div style="text-align:center">
    <marquee style="width:40px; color:red" behavior="scroll"  direction="left">.. . .</marquee>
</div>
<script>
function toHome(){
	document.location.href="/user/login";
}
setTimeout("toHome()",5000);
</script>
<?php }?>

<style>
body{
	background-color:white;
}
.container{
	width: 1000px;
	min-height: 600px
}
#forget-password-form-title{
	font-size: 19px;
    color: #007517;
    font-style: italic;
    margin-bottom: 5px;
}
.form-control{
	margin:5px;
}
#footer{
	background: white;
    border-top: 1px #F3F5F5 solid;
}
</style>